server:
  port: 8090
  max-header-size: 65536

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${COGNITO_JWKS_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: partner-service
        url: /partner-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: fulfilment-service
        url: /fulfilment-service/v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs
  cache:
    disabled: true
  use-management-port: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.platform: INFO
    org.springframework.cloud.gateway: INFO