server:
  port: 8090

app:
  version: 1.0.0-local

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${COGNITO_JWKS_URL}

logging:
  level:
    com.platform: INFO
    org.springframework.cloud.gateway: INFO