server:
  port: 8083

spring:
  application:
    name: fulfilment-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: fulfilment-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    properties:
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_API_KEY}" password="${KAFKA_API_SECRET}";

aws:
  region: ${AWS_REGION:ap-south-1}

logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","service":"fulfilment-service","correlationId":"%X{correlationId}","message":"%m"}%n'
  level:
    com.platform: INFO