server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: order-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${COGNITO_JWKS_URL}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    properties:
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_API_KEY}"
        password="${KAFKA_API_SECRET}";

feign:
  client:
    config:
      partner-service:
        connectTimeout: 2000
        readTimeout: 3000

aws:
  region: ${AWS_REGION:ap-south-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","service":"order-service","instance":"${SERVER_PORT:8082}","correlationId":"%X{correlationId}","message":"%m"}%n'